---
# tasks file for yum-cron

- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

##
# Note that the version specific setup must run first
##
- include: setup-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml
- include: setup-{{ ansible_os_family }}.yml

- name: ensure packages are installed
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ __yumcron_packages }}"
  register: __yum_cron_installed
  tags:
    - yumcron

- name: ensure machine is up to date
  yum:
    name: "*"
    state: latest
  when: yumcron_update_on_ansible_run or
          ( yumcron_update_on_first_run and __yum_cron_installed|changed )
  tags:
    - yumcron

- include: configure-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml

