---
# RedHat 7 yum-cron setup tasks

## Note that this _MUST_ run prior to setup-RedHat.yml
- name: define yumcron_emit_via
  set_fact:
    yumcron_emit_via: "{{ __yumcron_emit_via }}"
  when: yumcron_emit_via is not defined
  tags:
    - yumcron

